#!/usr/bin/env bash

MONITOR=$(xrandr -q | grep ' connected primary' | cut -d' ' -f1)
export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1) )
export MONITOR=${MONITOR:-${MONITORS[0]}}

for monitor in $MONITORS; do
  bspc monitor $monitor -d 0
done
bspc monitor $MONITOR -d {1,2,3,4,5}

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true


# Rules
bspc rule -r '*'

bspc rule -a Firefox split_ratio=0.32

# PiP windows
bspc rule -a firefox:Toolkit sticky=on state=floating

bspc rule -a feh state=fullscreen


for file in $XDG_CONFIG_HOME/bspwm/rc.d/*; do
  source "$file"
done
